#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : lrzip-next
Version  : 0.7.62
Release  : 1
URL      : https://github.com/pete4abw/lrzip-next/archive/refs/tags/v0.7.62.tar.gz
Source0  : https://github.com/pete4abw/lrzip-next/archive/refs/tags/v0.7.62.tar.gz
Summary  : lrzip-next compression library
Group    : Development/Tools
License  : GPL-2.0
Requires: lrzip-next-bin = %{version}-%{release}
Requires: lrzip-next-man = %{version}-%{release}
BuildRequires : bzip2-dev
BuildRequires : doxygen
BuildRequires : libgcrypt-dev
BuildRequires : libgpg-error-dev
BuildRequires : lz4-dev
BuildRequires : lzo-dev
BuildRequires : nasm-bin
BuildRequires : pkgconfig(zlib)
BuildRequires : yasm

%description
DECEMBER 2019
This is another update with LZMA SDK 19.00 with some modifications.
The Threads.c and Threads.h files are from p7ip-16.02. Small header
modifications made to MtCoder.h and Threads.h for lrzip. In addition,
lzma2 code has been imported (but not used yet) as well as the
Multi Thread lzma decoder, which also is not used yet.

%package bin
Summary: bin components for the lrzip-next package.
Group: Binaries

%description bin
bin components for the lrzip-next package.


%package doc
Summary: doc components for the lrzip-next package.
Group: Documentation
Requires: lrzip-next-man = %{version}-%{release}

%description doc
doc components for the lrzip-next package.


%package man
Summary: man components for the lrzip-next package.
Group: Default

%description man
man components for the lrzip-next package.


%prep
%setup -q -n lrzip-next-0.7.62
cd %{_builddir}/lrzip-next-0.7.62

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1625371576
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1625371576
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lrunzip
/usr/bin/lrz
/usr/bin/lrzcat
/usr/bin/lrzip-next
/usr/bin/lrztar
/usr/bin/lrzuntar

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/lrzip\-next/*

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/lrunzip.1
/usr/share/man/man1/lrz.1
/usr/share/man/man1/lrzcat.1
/usr/share/man/man1/lrzip-next.1
/usr/share/man/man1/lrztar.1
/usr/share/man/man1/lrzuntar.1
/usr/share/man/man5/lrzip-next.conf.5
